import mongoose from 'mongoose';

const CvProfileSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    photo: { type: String, required: false },
    passportCopy: { type: String, required: false },
    name: { type: String, required: true },
    fatherName: { type: String, required: true },
    cnic: { type: String, required: true },
    drivingLicence: { type: Number },
    dob: { type: Date, required: true },
    madicalDate: { type: Date },
    livingcity: { type: String },
    village: { type: String },
    gender: { type: String },
    passport: { type: String, required: true },
    passportIssue: { type: Date },
    passportExpiry: { type: Date, required: true },
    languages: { type: [String], required: true },
    countriesVisited: { type: [String], default: [] },
    email: { type: String },
    phone: { type: String, required: true },
    whatsapp: { type: String },
    otherNumber: { type: String },
    backupNumber: { type: String },
    backupEmail: { type: String },
    country: { type: String },
    state: { type: String },
    city: { type: String, required: true },
    localAddress: { type: String },
    jobTitle: { type: String, required: true },
    industry: { type: String, required: true },
    category: { type: String },
    subcategory: { type: String },
    jobDetails: { type: String },
    technicalEducation: { type: String },
    pakistaniDrivingLicense: { type: String },
    gulfDrivingLicense: { type: String },
    licenseType: { type: String },
    education: [],
    experience: [],
    skills: { type: [String] },
    attachments: { type: [String], default: [] }, 
    type: { type: String, enum: ['others', 'default', 'summary'], default: 'default' },
  },
  { timestamps: true }
);

export default mongoose.models.CvProfile || mongoose.model('CvProfile', CvProfileSchema);
