
import mongoose from 'mongoose';

const jobSchema = new mongoose.Schema({
  userId: String,
  jobTitle: String,
  companyName: String,
  jobType: String,
  country: String,
  state: String,
  salaryMin: Number,
  salaryMax: Number,
  industry: String,
  category: String,
  jobDescription: String,
  keyResponsibilities: [String],
  selectedSkills: [String],
  education: String,
  selectedTags: [String],
  image: String,
  license: String,
  dutyHours: String,
  overtime: String,
  duration: String,
  accommodation: String,
  medicalInsurance: String,
  transportation: String,
  returnTicket: String,
  firstDeparture: Date,
  interviewDate: Date,
  interviewVenue: String,
  interviewLocation: String,
  interviewAddress: String,
  visaNumber: String,
  navttc: String,
  visaCategory: String,
  createdAt: { type: Date, default: Date.now },
}, { timestamps: true });

export default mongoose.models.Job || mongoose.model('Job', jobSchema);